---
#image:
#  file: .gitpod.Dockerfile

vscode:
  extensions:
    - twxs.cmake@0.0.17:9s7m9CWOr6i6NZ7CNNF4kw==
    - ms-vscode.cmake-tools@1.2.3:qLtqI3aUcEBX9EpuK0ZCyw==

    - havogt.cmakels-client@0.0.2:g8cQRQz62ufKoQ821YvtmQ==

tasks:
  - init: |
      ln -s .gitpod/.vscode .
      ln -s .gitpod/.theia .
      mkdir build && cd build && cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON .. && cp compile_commands.json ..