name: CI-win

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@v1
      - name: configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe" -G Ninja ..
      - name: build
        run: cmake --build build --parallel 2
      - name: test
        run: |
          cd build
          ctest --output-on-failure
