name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]
        sanitize: ["", "-fsanitize=address", "-fsanitize=memory", "-fsanitize=undefined"]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build && cd build
        CXX=`which ${{ matrix.compiler }}` cmake .. -DCMAKE_CXX_FLAGS="${{ matrix.sanitize }}"
    - name: build
      run: cmake --build build --parallel 2
    - name: test
      run: cd build && ctest --output-on-failure
