name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir lscpp/build && cd lscpp/build
        CXX=`which ${{ matrix.compiler }}` cmake ..
    - name: build
      run: cmake --build lscpp/build --parallel 2
    - name: test
      run: cd lscpp/build && ctest -VV #--output-on-failure
    - name: print result
      run: cat test/integration/sample_server/sample_server.log
